server:
  port: 8083

spring:
  application:
    name: streammer-pocket
  servlet:
    multipart:
      max-file-size: 10024KB
      max-request-size: 10024KB

video:
  path: video-pocket.mp4
  size: 1535468
  ext: video-pocket.mp4

s3:
  access-key: AKIAIOSFODNN7EXAMPLE
  secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  host: http://localhost:9444/s3
  bucket: video