server:
  port: 8082

spring:
  application:
    name: streammer-hd
  servlet:
    multipart:
      max-file-size: 10024KB
      max-request-size: 10024KB

video:
  path: video-hd.mp4
  size: 5083276
  ext: video-hd.mp4

s3:
  access-key: AKIAIOSFODNN7EXAMPLE
  secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  host: http://localhost:9444/s3
  bucket: video